### PR TITLE
Ctrl030 - newest version of smart contracts branch

### PR DESCRIPTION
**Pull request by ctrl030**

### CODE REVIEW

**Comment by orbitmechanic** [comment]
Good greif.  This is MASSIVE.  Every one of those commits is MASSIVE.  There's just no way for me to humanly review this except relying on your unit tests running and then reading through the final contract code.   Going forward I'm going to ask for a PR per day.   There's a couple of instances along your journey where I outright anvil'd your efforts and deserve the trainload commit.  But the rest of it: slow and steady wins the race. My yoke is light, my burden is easy--but not if you drop boulder PR's like this.  I probably could have helped at not all, but "several" points along the way had you given me the PR chance to check in.  Next job: dazzle the boss with flurries of pretty little PR's.  They'll love it.

**Comment by orbitmechanic** [comment]
Netlify automated checks are up and running.  This PR passes them.  That tells me none of what you did broke the front-end.  So I'm going to presume the rebasing to master went well.

**Comment by orbitmechanic** [comment]
Merging sight-unseen, per previous comment.  Reviewing this is humanly impossible.  I'll have to read through the resulting master and run some tests to close issues against this PR.

**Comment by ctrl030** [comment]
Hey Bob, sorry for that, I didn't realize that would have been useful - no problem for the future! I thought since my branch and the master branch were not interacting at all, that I would have just created unnecessary work for you by sending in PR's. That's why I focused on doing 2-3 daily code pushes to my branch, but kept it there. But as I said, no problem, can do a daily PR or whatever frequency is most useful 👍

**Pull request merged**
