### PR TITLE
Thomas work

### PR DESCRIPTION
**Pull request by git-tn**
- Auto-add tokens we're swapping into into MetaMask list #115
- Updated portfolioContext (fix some issues)

### CODE REVIEW

**Review by orbitmechanic — APPROVED** [review]
Some of these files are mine and very old.  I'm ok with parting with them.

**Review by orbitmechanic — APPROVED** [review]
Cool web3 API call.  And I see you've done some research on our token data too.  Nice.

**Review by orbitmechanic — APPROVED** [review]
Are we using QuickSwap for all price data?  Ok.  That may bite us long term...in complex cases lacking arbitrage.

**Comment by git-tn** [comment]
> Are we using QuickSwap for all price data? Ok. That may bite us long term...in complex cases lacking arbitrage.

We are using coingecko api `api.coingecko.com/api/v3/coins/markets` for native token price and Moralis api `Moralis.Web3API.token.getTokenPrice()` for erc20 token prices.
Also, we are getting token images from coingecko api `api.coingecko.com/api/v3/coins/markets`.

**Pull request merged**
