### PR TITLE
Mobile Code

### PR DESCRIPTION
**Pull request by nyousaf47**
- PR for Mobile Code merge
- Commented Husky, Git Hooks and extra script for git from template.

### CODE REVIEW

**Comment by nyousaf47** [comment]
@orbitmechanic  can you merge this with master, this belongs to mobile app, all files and changes belongs to mobile project. 
Just commented few scripts/hooks regarding template, adding more steps for me to push any commit.

**Review by orbitmechanic — APPROVED** [review]
Looks like tuning up TypeScript.

**Review by orbitmechanic — APPROVED** [review]
Ez fix.  I bet that was not fun to diagnose.

**Review by orbitmechanic — APPROVED** [review]
Thank you.

**Review by orbitmechanic — APPROVED** [review]
Looks like cleaning up localizations.

**Pull request merged**
