### PR TITLE
Login Routes and Icon Transparency issue Fixed

### PR DESCRIPTION
**Pull request by nyousaf47**
- Linked #243 
- Linked #269 
- Added new routes for Login/Sign up
- Setup UI according to new Figma for both modes
- Copied functionality for Signup/login
- Fixed issue Icon transparency issue

### CODE REVIEW

**Review by orbitmechanic — APPROVED** [review]
Rebasing.

**Review by orbitmechanic — APPROVED** [review]
Nice.  That would have taken me a while to look up how to do it.  Thank you!

**Review by orbitmechanic — APPROVED** [review]
Is this a skeleton?

**Review by orbitmechanic — APPROVED** [review]
Rebasing.

**Review by orbitmechanic — APPROVED** [review]
Interesting mechanics.  We might chat about this.

**Comment by orbitmechanic** [comment]
I can't merge this to Master until it compiles cleanly.  Netlify deployment will break.  Please amend.
Screen Shot 2021-12-15 at 10 52 00 AM
.

**Comment by nyousaf47** [comment]
> I can't merge this to Master until it compiles cleanly. Netlify deployment will break. Please amend. Screen Shot 2021-12-15 at 10 52 00 AM .

OK, I am fixing this

**Pull request merged**
