### PR TITLE
Thomas token price

### PR DESCRIPTION
**Pull request by git-tn**
- Migrate price quotes from CoinGecko to Moralis #147
- Remove bogus token prices/balances from calculation of portfolio total values. #163
- Kill weird Metamask "Connect" button state. #165

### CODE REVIEW

**Review by orbitmechanic — APPROVED** [review]
I like moving things into contexts.
Adding geckoCoinIds.json?  I thought we were moving to Moralis for price data.
Looks a lot like my first attempt at a portfolio context.

**Review by orbitmechanic — APPROVED** [review]
Big tune up o fthe portfolio context...
Split tokens into files by network?  Ok.
Where did you get the Polygon token list from I wonder....

**Comment by git-tn** [comment]
> Big tune up o fthe portfolio context... Split tokens into files by network? Ok. Where did you get the Polygon token list from I wonder....

Polygon token list is from [1inch](https://docs.1inch.io/api/tokens)

https://api.1inch.exchange/v3.0/137/tokens

**Comment by git-tn** [comment]
> I like moving things into contexts. Adding geckoCoinIds.json? I thought we were moving to Moralis for price data. Looks a lot like my first attempt at a portfolio context.

`geckoCoinIds.json` is also used in portfolio table component, Rumi seems still using it.

**Pull request merged**
