### PR TITLE
Thomas work

### PR DESCRIPTION
**Pull request by git-tn**
- Return to default expert dialog/character upon logging out on the log-in screen. #282
- Redesign expert panel graphics #284
- Upgrade the Home Page Token List display from "adequate" to "OMG" #286

### CODE REVIEW

**Review by orbitmechanic — APPROVED** [review]
Nonce.

**Review by orbitmechanic — APPROVED** [review]
Looks like good catches.

**Review by orbitmechanic — APPROVED** [review]
Yeah, that was some formatting changes.  Not quite the directory structure I'd set up, but ok.

**Comment by orbitmechanic** [comment]
Looks like a path problem with one or more .svg files.

**Comment by git-tn** [comment]
resolved conflicts. please pull.

**Pull request merged**
