### PR TITLE
updated research card

### PR DESCRIPTION
**Pull request by rumi-art**

### CODE REVIEW

**Review by orbitmechanic — APPROVED** [review]
This looks interesting...

**Review by orbitmechanic — CHANGES_REQUESTED** [review]
Something's not right though.  Netlify checks are failing on this commit.  Are you sure it compiles?

**Comment by rumi-art** [comment]
I didn't change anything for deploy.

**Comment by orbitmechanic** [comment]
Interesting.  Given Prettier's track record I doubt Prettier is the problem.  Millions of other devs use Prettier without incident.  I see no changes to Prettier in this commit.  However I do see a version update Babel in your yarn.lock and I know Babel is a critical dependency to a ReactJS project.  I suspect this is the real cause of Netlify's issue.

**Comment by orbitmechanic** [comment]
Ok, so I checked the Netlify logs.  You did not cause this issue.  I did.  Somehow Netlify is trying to compile outside the website/ directory and chokes on the new mobileap/ directory I installed.  Error message is as follows: 

`12:15:22 PM: Failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'mobileap' in .gitmodules`

I will merge your commit and deal with this error elsewhere.

**Pull request merged**
